### ISSUE TITLE
Components needing point releases in 0.15

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt.github.io#43]
I think they are:

 * lxqt-panel (because of https://github.com/lxqt/lxqt-panel/issues/1391, which apparently was a critical issue for some).
 * pcmanfm-qt (because of https://github.com/lxqt/pcmanfm-qt/issues/1106 and https://github.com/lxqt/pcmanfm-qt/issues/1103).
 * libfm-qt (only because pcmanfm-qt needs it).
 * lxqt-archiver (actually it doesn't need a "point release" but it's good to release 0.2.0).

If you know of another component or have any objection, please tell me.

**Comment by jubalh** [comment]
Looks good. Nothing more to add from my side. All seems working fine.

**Comment by luis-pereira** [comment]
Nothing more.
Tested https://github.com/lxqt/lxqt-panel/issues/1391, works fine. Although I was not able to reproduced it.

**Comment by tsujan** [comment]
@jubalh @luis-pereira Thanks! I'll make those releases in < 2 weeks (just to see if another critical bug is found).

**Comment by tsujan** [comment]
@jubalh @yan12125 
libfm-qt 0.15.1, pcmanfm-qt 0.15.1 and lxqt-archiver 0.2.0 are released.

**Comment by tsujan** [comment]
Ah, please wait! pcmanfm-qt 0.15.1 has a problem! I'm fixing it.

**Comment by tsujan** [comment]
False alarm. Everything is OK.

**Comment by yan12125** [comment]
Awesome! I uploaded all of three new packages to Arch Linux.

**Comment by jubalh** [comment]
Awesome indeed! I updated the openSUSE packages too.

**Comment by tsujan** [comment]
@Chiitoo
I forgot to tell you about 0.15.1 here (for Gentoo).

**Comment by Chiitoo** [comment]
Thanks!

I do watch each repository, so I was already aware (except for this one... actually... time to fix that!).

**Comment by tsujan** [comment]
@jubalh @yan12125 @Chiitoo 
lxqt-panel 0.15.1 is released.

**Comment by jubalh** [comment]
openSUSE package is updated! Thanks!

**Comment by tsujan** [comment]
That was very fast -- I hadn't signed out of GitHub.

**Comment by yan12125** [comment]
Uploaded the latest lxqt-panel to Arch, too :)

**Comment by Chiitoo** [comment]
Thanks!

With that, all of release 0.15 is available via the Gentoo repositories as well (without relying on git builds that is).

**Comment by tsujan** [comment]
Nice.

The more users the latest release has, the more useful reports we might get. Most users think git is unstable.
