### ISSUE TITLE
Please add FreeBSD as a supported system.

### ISSUE THREAD

**Issue by jsm222** [lxqt/lxqt.github.io#52]
Hi
Could FreeBSD be listed on the https://lxqt-project.org/ as supported system?
Thanks.

**Comment by palinek** [comment]
Can you, please, share URL to link to and (official) logo picture?

**Comment by jsm222** [comment]
The logo information page is  [here](https://freebsdfoundation.org/about-us/about-the-foundation/project/)
The logo package is [here](https://freebsdfoundation.org/wp-content/uploads/2016/05/FreeBSDLogoArchive.zip)
I suggest to use "FreeBSD Logo Archive/Vertical/Full Color/Positive/RGB/FREEBSD_Logo_Vert_Pos_RGB.png"
Info on LXQt on FreeBSD is at [wiki.FreeBsd.org/LXQt](https://wiki.FreeBsd.org/LXQt)

**Comment by stefonarch** [comment]
Had just a look at the logo information - as you can see all logos are the same 22px white on our list and all fonts are the same.
Now "Don't alter the logo in any way" would just exclude to adapt it here (just use the white icon with transparent background).

**Comment by jsm222** [comment]
Yes I guess the full logos does not fit in. Perhaps this icon or similar is a legal option https://www.iconfinder.com/icons/4373729/freebsd_logo_logos_icon

**Comment by stefonarch** [comment]
I could use that but would have to turn it white.

**Comment by jsm222** [comment]
Have a look at https://people.freebsd.org/~jsm/lxqt_io/test.html and https://people.freebsd.org/~jsm/lxqt_io/fbsd.png
Thanks

**Comment by stefonarch** [comment]
Both are black lines on transparent background...

**Comment by jsm222** [comment]
oh, try https://people.freebsd.org/~jsm/lxqt_io/test.html and https://people.freebsd.org/~jsm/lxqt_io/fbsd1.png

**Comment by stefonarch** [comment]
Thanks!
Preview:  https://github.com/lxqt/lxqt.github.io/pull/61#issuecomment-808673554
