### ISSUE TITLE
Certbot renewal issue?

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt.github.io#53]
Related probably to https://github.com/lxqt/lxqt.github.io/pull/50
Probably a temporary issue from GH, see test in bottom.

~100 email from the server, not sure if those are really errors because https://lxqt-project.org/ looks good and gives no error.

```
Broken project website URL

This project is set up incorrectly.

The project website URL points to a non-existing location:

    https://lxqt-project.org/ (HTTPSConnectionPool(host='lxqt-project.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)'))))
```
Renewal from the server:

```
Processing /etc/letsencrypt/renewal/lxqt-project.org.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator nginx, Installer nginx
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for lxqt-project.org
Using default addresses 80 and [::]:80 ipv6only=on for authentication.
Waiting for verification...
Challenge failed for domain lxqt-project.org
http-01 challenge for lxqt-project.org
Cleaning up challenges
Attempting to renew cert (lxqt-project.org) from /etc/letsencrypt/renewal/lxqt-project.org.conf produced an unexpected error: Some challenges have failed.. Skipping.                                                                                                                 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/translate.lxqt-project.org.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert not yet due for renewal
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/lxqt-project.org/fullchain.pem (failure)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/translate.lxqt-project.org/fullchain.pem expires on 2021-03-01 (skipped)
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/lxqt-project.org/fullchain.pem (failure)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1 renew failure(s), 0 parse failure(s)

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: lxqt-project.org
   Type:   unauthorized
   Detail: Invalid response from
   http://lxqt-project.org/.well-known/acme-challenge/VXigrrKYokJ1RkajyFjBUjICi0QtH6y_WyldYPrAG5E
   [185.199.111.153]: "<!DOCTYPE html>\n<html>\n  <head>\n    <meta
   http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\">\n
   <meta http-equiv=\"Co"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

```

185.199.111.153 is one of  the   github.io IP 's now 404

![schermata-11-55-55](https://user-images.githubusercontent.com/10681413/103437460-53026200-4c28-11eb-8f5a-c989676644ff.png)

**Comment by stefonarch** [comment]
Hm, weblate displays in the GUI still errors for all components which refers to https://lxqt-project.org/ as project website (desktop, configuration) -  changing to http all those errors disappear, did so to avoid other 100 email next night.

**Comment by yan12125** [comment]
`/etc/hosts` on the server has `135.181.85.100  lxqt-project.org weblate`, so requests from the server goes to the wrong IP (it should be the GitHub IP after https://github.com/lxqt/lxqt.github.io/pull/50). I changed that line to `135.181.85.100 weblate` to see if it fixes the issue.

**Comment by stefonarch** [comment]
Looks solved, switching back to https://lxqt-project.org/ in projects settings shows no errors now.
Thanks, didn't think of this file. Hopefully emails with riseup will still work now ;)

**Comment by yan12125** [comment]
The mail is still working! I received both test mails from Weblate.

**Comment by stefonarch** [comment]
The problem was with riseup, no IP for the domain in /etc/hosts and thee ended not even in spam but got blocked before.
The first didn't arrive, the other 2 yes, so hoping for the best.

**Comment by yan12125** [comment]
This seems the error message for a failed mail delivery
```
504 5.5.2 <weblate>: Helo command rejected: need fully-qualified hostname
```

So I took some steps:
1. Change the name in hello command following https://unix.stackexchange.com/a/544323
2. Change the reverse DNS to translate.lxqt-project.org from Hetzner console

Could you try again to see if it works for riseup.net?

**Comment by stefonarch** [comment]
I received 2 emails 1½ hour ago, so looks fine.
