### ISSUE TITLE
Add more distros to list

### ISSUE THREAD

**Issue by gitpubber** [lxqt/lxqt.github.io#55]
Lxqt website has list of distros the Lxqt supports.

Please add Alpine linux, artix linux, void linux to the list

**Comment by stefonarch** [comment]
Going trough the existing links:
https://ccr.chakralinux.org/packages.php?O=0&K=lxqt&do_Search=+Go+
I didn't find anything better than 0.11 so it should be removed from the list.

**Comment by comradekingu** [comment]
@stefonarch I think asking if they could update is a better option.
