### ISSUE TITLE
Website is boring

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt.github.io#92]
##### Expected Behavior

Some more articles as only release posts; news, howtos ecc

##### Possible Solution

Reopen blog or eventually a "news" section.
##### Context

Twitter reaches some people, others should find something too.

**Comment by stefonarch** [comment]
Created an "Articles" category, looks working. Reorganized also the "Release" page.

![schermata-02-02-20-11](https://user-images.githubusercontent.com/10681413/152221548-d56e9969-f577-4e87-a732-f8ce33bcc387.png)

![schermata-02-02-20-09](https://user-images.githubusercontent.com/10681413/152221551-d8026ee5-9626-452b-b5e0-1439386b4b37.png)

**Comment by tsujan** [comment]
Seems nice.

**Comment by stefonarch** [comment]
Maybe better split the commits:
1. new layout for "releases", 3 instead of 5 features posts in home
2.  open article category, needs an little change in css for inserting images 
3. posting articles (or better name it blog or else?)
![schermata-02-02-23-00](https://user-images.githubusercontent.com/10681413/152245242-af4b38df-523c-459e-af99-6053e671262a.png)
